### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wang1784594241** [tensorfly-gpu/PPdiffusers-webui#1]
ERROR: No matching distribution found for paddlepaddle-gpu==2.4.2.post112
Traceback (most recent call last):
  File "/home/aistudio/PPdiffusers-webui/launch.py", line 37, in <module>
    start()
  File "/home/aistudio/PPdiffusers-webui/launch.py", line 32, in start
    import webui
  File "/home/aistudio/PPdiffusers-webui/webui.py", line 6, in <module>
    import utils
  File "/home/aistudio/PPdiffusers-webui/utils.py", line 18, in <module>
    requires_safety_checker=False)
  File "/home/aistudio/PPdiffusers-webui/ppdiffusers/pipeline_utils.py", line 366, in from_pretrained
    config_dict = cls.load_config(pretrained_model_name_or_path)
  File "/home/aistudio/PPdiffusers-webui/ppdiffusers/configuration_utils.py", line 363, in load_config
    f"Error no file named {cls.config_name} found in directory {pretrained_model_name_or_path}."
OSError: Error no file named model_index.json found in directory /home/aistudio/PPdiffusers-webui/models/NovelAI_latest_ab21ba3c_paddle.

**Comment by tensorfly-gpu** [comment]
# 已经修复了
